### PR TITLE
enhancement for #84

### PR DESCRIPTION
**Pull request by 0xblackbird**
I've created a new function for this to not mess up with the other (search_tags). The way this works is it queries couchdb and filters the keys and values needed. It then checks if both of the values and keys are in the tags. If so, it returns the document id.
Unsure if this is the most efficient way to do this (I couldn't find a way to implement this via views on couchdb). 
Please do test the this and see if it works for you, thanks! Have a nice day!

### CODE REVIEW

**Review by honoki — COMMENTED** [review]
Hi @0xblackbird - thanks a lot for your contributions! I agree that the limitations of CouchDB, and there will need to be some logic inside the client to make this syntax work.

I had a look at your code, and believe this does not do exactly what is intended. For example:

```bash
bbrf new test
bbrf inscope add '*.test.com'
bbrf domain add one.test.com -t color:blue -t shape:rectangle
bbrf domain add two.test.com -t color:blue -t shape:square
```
Now querying the data (with curl):
```bash
curl -k $(jq -r .couchdb ~/.bbrf/config.json)'/_design/bbrf/_view/search_tags?key=\["color","blue"\]' -u bbrf:$(jq -r .password ~/.bbrf/config.json)
```
This finds 2 results, as expected.

Now using the query you suggest:
```bash
curl -k $(jq -r .couchdb ~/.bbrf/config.json)'/_design/bbrf/_view/search_tags?startkey=\["color","blue"\]&endkey=\["shape","square"\]' -u bbrf:$(jq -r .password ~/.bbrf/config.json)
```
In other words, grabbing all tags with values between `["color","blue"]` and `["shape","square"]` returns 1.9 million tags on my dataset, whereas we would only expect one. :)

The reason is that CouchDB view collation works in a particular way - I would recommend you read about it on https://docs.couchdb.org/en/stable/ddocs/views/collation.html

So to achieve this, I think the way forward is an algorithmic approach built inside the client that does:
1. retrieve every record that matches the first clause;
2. filter out anything that doesn't match the second (third, etc.) clause(s).

An or operator would be easier, as it would come down to combining results of two separate queries.

**Comment by honoki** [comment]
I just realized I overlooked one of the instructions that filters out only matching documents. Apologies!

So that means your code will work in the provided example. (I still think there may be some edge casss where couchdb is tricky.) 

My other main concern is performance, as in my previous example the second request takes ~20 seconds. I'm wondering if a client-side implementation will always beat Couchdb's query or if we may need to take some hybrid approach. 

Food for thought!

**Comment by 0xblackbird** [comment]
Yeah, I was wondering the same, after hours spent on searching in couchdb docs and just on the internet in general, it doesn't seem that there's a way to do this with couchdb. That's why I thought of using a workaround for this, same steps just like you mentioned. 
However, you could also go for another approach by sending 2 (or more) different requests to the search_tags view each with a key and value and retrieve these results and individually check if each of the results have the same tags. I guess that this would be more inefficient than this approach.

I also knew from the beginning that it will not be the most efficient way of doing this. But we can always look for other ways of doing this as this is still fairly limited to only match 2 different tags and values.

And as you pointed out, the or operator is indeed easier, you could implement this in the couchdb view like you said by emitting the 2 results of both queries.

**Comment by honoki** [comment]
Closing this since this is implemented in 1.3.0

**Pull request closed without merging**
